// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClitb5RS_aNMkSPJ2mbq8iDiVxhMpKVU8',
    appId: '1:242904742:web:535ddde5215a3e25634e67',
    messagingSenderId: '242904742',
    projectId: 'chatapp-69658',
    authDomain: 'chatapp-69658.firebaseapp.com',
    storageBucket: 'chatapp-69658.firebasestorage.app',
    measurementId: 'G-6JQE6YZ587',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvi1iJE4n0q7L0MIIZy3TSoq-E_QNipqY',
    appId: '1:242904742:android:3e379cba50451c8e634e67',
    messagingSenderId: '242904742',
    projectId: 'chatapp-69658',
    storageBucket: 'chatapp-69658.firebasestorage.app',
  );
}
